services:

  postgres:
    image: postgres:16
    container_name: hireme-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hireme

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-script/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d hireme"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: hireme-keycloak
    restart: unless-stopped

    command:
    - start-dev
    - --import-realm

    volumes:
    - ./init-script/keycloak:/opt/keycloak/data/import

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: